- src/operator.rs
This PR adds `square_euclidean_distance` for different types and more test cases. PTAL thanks!
> feat: implement square_euclidean_distance for f32, f64 and i32

- .all-contributorsrc
- README.md
> chore: Update readme

- .github/workflows/check.yml
- .github/workflows/release.yml
Nightly releases will be built on 00:00 UTC+8 if there are any commits in the past 24 hours.
> feat: add ci for nightly release

- README.md
> Fold build from source

- .dockerignore
- Dockerfile
- README.md
- docker.sh
`CREATE EXTENSION vectors` should be performed manually.
> feat: dockerfile

- .github/workflows/release.yml
> Fix github action release

- README.md
Signed-off-by: Jinjing Zhou <VoVAllen@users.noreply.github.com>
> [readme] fix readme

- .cargo/config.toml
- Cargo.toml
- README.md
- src/algorithms/impls/mod.rs
- src/algorithms/impls/vamana.rs
- src/algorithms/mod.rs
- src/algorithms/vamana.rs
> feat: vamana

- README.md
- docs/comparison-with-specialized-vectordb.md
This reverts commit 60658667ca916b0d3fc197d32d6cadc8a5cc7304.
> Revert "Update readme (#84)"

- src/algorithms/impls/vamana.rs
_robust_prune with argument r and avoiding directly call of unwrap inside _robust_prune
> fix: vamana logical error

- .github/workflows/check.yml
- .github/workflows/release.yml
Fix https://github.com/tensorchord/pgvecto.rs/actions/runs/6701671369/job/18209452281#step:5:143 .
> fix: disable cache for cargo binary

- bindings/python/README.md
- bindings/python/examples/psycopg_example.py
- bindings/python/examples/sqlalchemy_example.py
- bindings/python/pyproject.toml
- bindings/python/src/pgvecto_rs/psycopg/__init__.py
- bindings/python/tests/__init__.py
- bindings/python/tests/test_psycopg.py
- bindings/python/tests/test_sqlalchemy.py
> feat: add Python bindings by psycopg 3

- src/postgres/casts.rs
> fix: mark cast functions immutable

- docker/pgvecto-rs.Dockerfile
- docker/scripts/docker.sh
> chore: start bgworker by postgresql args in dockerfile

- .github/workflows/release.yml
> ci: fix typo

- src/index/delete.rs
> fix: truncate WAL after restarting

- .github/workflows/release.yml
- docker/pgvecto-rs.Dockerfile
> ci: multi arch image

- .github/workflows/release.yml
> ci: Update Docker build arguments

- README.md
> doc: fix wrong layout

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- docs/installation.md
- scripts/ci_setup.sh
- scripts/envd.sh
- src/bgworker/mod.rs
- src/bgworker/worker.rs
- src/index/mod.rs
- src/ipc/client.rs
- src/ipc/packet.rs
- src/ipc/server.rs
- src/postgres/hook_executor.rs
- src/postgres/hook_transaction.rs
- src/postgres/hooks.rs
- src/postgres/index.rs
- src/postgres/index_build.rs
- src/postgres/index_scan.rs
- src/sql/finalize.sql
- tests/sqllogictest/reindex.slt
close #154
fix:
- Reindexing fails due to existing old index
- Droping index may not to remove dir because optimizing thread holds index arc when parking
> fix: reindex failed due to existing old index

- .github/workflows/release.yml
close https://github.com/tensorchord/pgvecto.rs/issues/168
> fix: empty nightly github release

- docs/searching.md
- src/algorithms/hnsw.rs
- src/bgworker/mod.rs
- src/bgworker/worker.rs
- src/index/indexing/hnsw.rs
- src/index/indexing/mod.rs
- src/index/mod.rs
- src/index/segments/growing.rs
- src/index/segments/sealed.rs
- src/ipc/client.rs
- src/ipc/packet.rs
- src/ipc/server.rs
- src/postgres/gucs.rs
- src/postgres/hook_executor.rs
- src/postgres/hook_transaction.rs
- src/postgres/index.rs
- src/postgres/index_scan.rs
- src/prelude/heap.rs
- src/utils/mmap_array.rs
- tests/sqllogictest/vbase.slt
> feat: vbase optimization

- src/datatype/vecf16.rs
- src/datatype/vecf32.rs
> fix: allow NAN, INFINITY, case case insensitive in parsing

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- scripts/ci_release.sh
> ci: bump release version

- .github/workflows/nightly.yml
> ci: fix nightly release timezone

- .cargo/config.toml
- .github/workflows/check.yml
- .github/workflows/release.yml
- docs/installation.md
- scripts/ci_setup.sh
> fix: do not config cross compilation in config.toml, document it in docs

- crates/service/src/index/mod.rs
- crates/service/src/worker/instance.rs
- docs/searching.md
- src/bgworker/mod.rs
- src/gucs.rs
- src/index/am_scan.rs
- src/ipc/client/mod.rs
- src/ipc/packet/mod.rs
- src/ipc/server/mod.rs
- tests/sqllogictest/vbase.slt
> feat: allow user to set vbase range

- .github/workflows/release.yml
Fix #200
- Removed all `latest` tags now
- Add a **commented** filter to generate `latest` only for manual triggered `release` script
> chore: stable latest

- .github/workflows/release.yml
- scripts/ci_package.sh
- sql/upgrade/vectors--0.1.0--0.1.1.sql
- sql/upgrade/vectors--0.1.1--0.1.2.sql
- sql/upgrade/vectors--0.1.10--0.1.11.sql
- sql/upgrade/vectors--0.1.11--0.1.12.sql
- sql/upgrade/vectors--0.1.12--0.1.13.sql
- sql/upgrade/vectors--0.1.2--0.1.3.sql
- sql/upgrade/vectors--0.1.3--0.1.4.sql
- sql/upgrade/vectors--0.1.4--0.1.5.sql
- sql/upgrade/vectors--0.1.5--0.1.6.sql
- sql/upgrade/vectors--0.1.6--0.1.7.sql
- sql/upgrade/vectors--0.1.7--0.1.8.sql
- sql/upgrade/vectors--0.1.8--0.1.9.sql
- sql/upgrade/vectors--0.1.9--0.1.10.sql
> chore: upgrade scripts for unsupported version

- README.md
- build.envd
- crates/service/src/prelude/error.rs
- docs/configuration.md
- docs/development.md
- docs/get-started.md
- docs/installation.md
- docs/upgrade.md
- scripts/envd.sh
> docs: development docs

- .github/workflows/check.yml
- tests/crash/create.slt
- tests/crash/kill.py
- tests/crash/restore.slt
Part of https://github.com/tensorchord/pgvecto.rs/issues/215
This is a test of Crash Recovery.
> chore: add crash test

- scripts/envd.sh
* https://github.com/tensorchord/pgvecto.rs/pull/265
* https://github.com/tensorchord/pgvecto.rs-docs/pull/11
> docs: advice developers to setup all PostgreSQL versions

- tests/sqllogictest/fp16.slt
- tests/sqllogictest/index.slt
- tests/sqllogictest/partition.slt
Related to #215 and fix #268
- Partition index from #215 at `partition.slt`
- Partial index from #215 at `partition.slt`
- Multiple index on single column from #215 added at `index.slt`
- fp16 index from #268 at `fp16.slt`
> chore: add test for partition/partial/fp16 index

- tests/sqllogictest/drop_index_when_indexing.slt
Fix task 6 in https://github.com/tensorchord/pgvecto.rs/issues/215.
> chore: Add test for dropping index when indexing

- .github/workflows/release.yml
- docker/pgvecto-rs-rootless.Dockerfile
Fix #261 
Build `pg14-${tag}-rootless`, `pg15-${tag}-rootless`, `pg16-${tag}-rootless` at release.
> chore: add rootless image

- sql/install/vectors--0.2.0.sql
- sql/upgrade/vectors--0.1.11--0.2.0.sql
- sql/upgrade/vectors--0.1.13--0.2.0.sql
- sql/upgrade/vectors--0.1.8--0.2.0.sql
- src/bgworker/normal.rs
- src/bgworker/upgrade.rs
- src/index/functions.rs
- src/index/mod.rs
- src/ipc/client/mod.rs
- src/ipc/packet/mod.rs
- src/ipc/packet/upgrade.rs
- src/ipc/server/mod.rs
- src/sql/finalize.sql
closes #312
* pgvecto.rs: https://github.com/tensorchord/pgvecto.rs/pull/313
* pgvecto.rs-docs: https://github.com/tensorchord/pgvecto.rs-docs/pull/38
> refactor: refine upgrade process

- src/datatype/vecf16.rs
- src/datatype/vecf32.rs
> fix: workaround for upgrading from version <= 0.1.11

- src/datatype/casts_f32.rs
- tests/sqllogictest/cast.slt
It can be merge even if 0.2.0 is not released.
> chore: nicer cast error message

- src/gucs/planning.rs
cc @cutecutecat 
cc @VoVAllen 
closes #330
> chore: set `vbase` as default search mode

- Cargo.lock
- Cargo.toml
- src/datatype/vecf16.rs
- src/datatype/vecf32.rs
- src/utils/mod.rs
- src/utils/parse.rs
- tests/sqllogictest/cast.slt
bench code: https://gist.github.com/usamoi/6af5bbc6407d508806a5250f5c450494
> refactor: faster algorithm for parsing vector strings

- .github/workflows/nightly.yml
cc @VoVAllen have you add the `NIGHTLY_TOKEN` to secrets?
refer to https://github.com/tensorchord/pgvecto.rs/pull/303
> chore: fix the nightly trigger condition

- crates/service/src/index/mod.rs
- crates/service/src/instance/mod.rs
- src/bgworker/normal.rs
- src/bgworker/upgrade.rs
- src/index/am_update.rs
- src/index/hook_transaction.rs
- src/ipc/client/mod.rs
- src/ipc/packet/delete.rs
- src/ipc/packet/drop.rs
- src/ipc/packet/flush.rs
- src/ipc/packet/list.rs
- src/ipc/packet/mod.rs
- src/ipc/server/mod.rs
- tests/sqllogictest/index_vacuum.slt
> refactor: refine delete RPC

- docker/pgvecto-rs-rootless.Dockerfile
- docker/pgvecto-rs.Dockerfile
- scripts/ci_install.sh
- src/lib.rs
> chore: add '-c logging_collector=on' to docker CMD

- .github/workflows/check.yml
- .github/workflows/release.yml
- scripts/ci_install.sh
- scripts/ci_setup.sh
Before: https://github.com/tensorchord/pgvecto.rs/actions/runs/7957439632/usage (13m 14s)
After: https://github.com/tensorchord/pgvecto.rs/actions/runs/7957784448/usage (6m 44s)
> ci: increase concurrency

- README.md
> doc: fix docker tag

- Cargo.lock
- Cargo.toml
- src/bin/pgrx_embed.rs
- src/sql/finalize.sql
Update pgrx version to a patch of pgrx which I was working on.
> chore: update pgrx version

- .github/workflows/check.yml
- scripts/build_0.sh
- scripts/build_2.sh
- src/lib.rs
- tools/schema-codegen.sh
- tools/schema.sh
> ci: remove cargo-pgrx in ci

- src/index/am_scan.rs
- tests/sqllogictest/issue_427.slt
> fix: returns no tuples when a NULL query comes

- src/datatype/functions_svecf32.rs
- src/sql/bootstrap.sql
- src/sql/finalize.sql
- tests/sqllogictest/svector.slt
Temporary support for sparse aggregate.  This will be replace by #476.
> feat: temporary support for sparse aggregate. 

- tests/sqllogictest/bvector.slt
> test: fix flaky test in bvector.slt

- crates/base/src/index.rs
- crates/quantization/src/lib.rs
- crates/quantization/src/operator.rs
- crates/quantization/src/product/mod.rs
- crates/quantization/src/product/operator.rs
- crates/quantization/src/scalar/mod.rs
- crates/quantization/src/scalar/operator.rs
> feat: quantization, 1/2/4 bits

- crates/ivf/src/lib.rs
https://github.com/tensorchord/pgvecto.rs/pull/535#discussion_r1692551451
> fix: load ivf_residual files with IvfResidual

- crates/base/src/aligned.rs
- crates/base/src/scalar/emulate.rs
- crates/base/src/scalar/f16.rs
- crates/base/src/scalar/f32.rs
- crates/base/src/scalar/impossible.rs
- crates/base/src/scalar/mod.rs
- crates/base/src/vector/svect.rs
- crates/base/src/vector/vect.rs
- crates/k_means/src/elkan.rs
- crates/k_means/src/lib.rs
- crates/k_means/src/lloyd.rs
- crates/quantization/src/product/mod.rs
- crates/quantization/src/quantize.rs
- crates/quantization/src/scalar/mod.rs
- crates/rabitq/src/operator.rs
fix:
1. computing max, min correctly
2. rounding quantized value by `round_ties_even`
> feat: SIMD version of quantizing

- crates/rabitq/src/lib.rs
- crates/rabitq/src/operator.rs
- crates/rabitq/src/quant/quantization.rs
- crates/rabitq/src/quant/quantizer.rs
> feat: do not generate slow-scan lookup table if fast-scan is enabled

- crates/rabitq/src/quant/quantization.rs
- crates/rabitq/src/quant/quantizer.rs
> feat: speed rabitq building

- crates/base/src/search.rs
- src/index/utils.rs
> fix: reduce length of directory name

- docker/pg-slim/Dockerfile
fix action https://github.com/tensorchord/pgvecto.rs/actions/runs/11679434558/job/32520511574
> fix dockerfile pg version error

- sql/upgrade/vectors--0.3.0--0.4.0.sql
> fix: confict typmod for _vectors_cast_array_to_vecf32
