README.md, build.envd
`pgrx` requires lots of build tools. It's really convenient to get the out-of-box dev environment with `envd`.
=> feat: add envd for dev env

README.md
try to fix #26 by adding type casts to queries in README `create table` section
=> doc: add type casts to README

Cargo.toml, src/embedding.rs, src/gucs.rs, src/lib.rs, src/udf.rs
#23 
This PR adds the `ai_embedding_vector` UDF which depends on OpenAI Ada002.
Example:
First, set openai_api_key
```
SET openai_api_key=<your-api-key>;
```
Query
```sql
SELECT ai_embedding_vector('hello') <-> ai_embedding_vector('hallo');
```
Output
```
?column?       
---------------------
0.29756917700636787
(1 row)
```
More complicated example
```sql
CREATE TABLE documents (id bigserial PRIMARY KEY, content VARCHAR, emb numeric[]);
INSERT INTO documents (content) VALUES ('Hello World!'), ('Rust Power'), ('Python World');
UPDATE documents SET emb = ai_embedding_vector(content);
SELECT content FROM documents ORDER BY emb <-> ai_embedding_vector("World") LIMIT 2;
```
Output is
```
content    
--------------
Hello World!
Python World
(2 rows)
```
=> feat: udf ai_embedding_vector

.github/workflows/check.yml, src/index/mod.rs
`am_routine.amusemaintenanceworkmem`and `am_routine.amoptsprocnum` added in pg13
also add CI and fix the old CI for it.
passed CI can check: https://github.com/yihong0618/pgvecto.rs/actions/runs/5400551415
fix #34 
Signed-off-by: yihong0618 <zouzou0208@gmail.com>
=> feat: support pg11 and pg12

README.md
Following the example in readme, there is no column called `emb` so updated it to the correct name.
=> Update sql in readme

.cargo/config.toml
Currently releases built by GitHub runners cannot run on machines without AVX-512 instructions. "x86-64-v3" relaxs the restriction for target instruction sets.
=> fix: use x86-64-v3 as target cpu

README.md, src/postgres/gucs.rs, src/postgres/index.rs, src/postgres/index_scan.rs
close #65
When using skip mode,
```
explain select train.id from train order by 'a long vector' <=> train.embedding limit 32;
Limit  (cost=490.54..499.02 rows=32 width=12)
->  Result  (cost=490.54..1815.81 rows=5001 width=12)
->  Sort  (cost=490.54..503.05 rows=5001 width=8)
Sort Key: (('a long vector'::vector <=> embedding))
->  Seq Scan on train  (cost=0.00..340.51 rows=5001 width=8)
```
When using prefilter/postfilter, 
```
explain select train.id from train order by 'a long vector' <=> train.embedding limit 32;
Limit  (cost=0.00..10.20 rows=32 width=12)
->  Index Scan using train_embedding_idx on train  (cost=0.00..1593.76 rows=5001 width=12)
Order By: (embedding <=> 'a long vector'::vector)
```
And when using postfilter, it will output "Fallback to post-filter." like …
=> feat: add GUC option to manually control filter mode

.github/workflows/check.yml, .github/workflows/release.yml, src/lib.rs
Update:
- complete e2e test ci
- add github cache to avoid installing `pgrx` and `sqllogictest`.
- add `sccache` to share cache for each compilation of rust code. We don't use github cache directly because incremental compilation of rust will make the cache dir becoming larger and lager.
=> ci: run ci when updating tests dir

src/bgworker/filter_delete.rs, src/bgworker/index.rs, src/bgworker/mod.rs, src/ipc/client.rs, src/ipc/packet.rs, src/ipc/server.rs, src/postgres/index.rs, src/postgres/index_build.rs, src/postgres/index_update.rs, tests/sqllogictest/operator.slt, tests/sqllogictest/update.slt
Update:
- update `ambuild` to return build result
- update `ambulkdelete` to support general callback function
- update delete rpc to scan for all existing vector keys and call the callback function
- add tests for `CREATE INDEX CONCURRENTLY`, `REINDEX CONCURRENTLY`, `UPDATE`, `DELETE`
- add log info in rpc handle
Close #72
=> feat: support concurrent index building

src/postgres/datatype.rs
Disallow type `vector(0)` so that we only accept `vector`, `vector(1)`, ... `vector(65535)`.
=> fix: disallow  type `vector(0)`

.github/workflows/release.yml
Set pg16 as the latest version for simplicity
=> ci: fix latest image

crates/service/src/algorithms/ivf/ivf_naive.rs, crates/service/src/algorithms/ivf/ivf_pq.rs, crates/service/src/algorithms/ivf/mod.rs, crates/service/src/index/indexing/flat.rs, crates/service/src/index/indexing/hnsw.rs, crates/service/src/index/indexing/ivf.rs, crates/service/src/index/indexing/mod.rs, crates/service/src/index/mod.rs, crates/service/src/index/segments/mod.rs, crates/service/src/index/segments/sealed.rs, crates/service/src/worker/instance.rs, crates/service/src/worker/mod.rs, docs/indexing.md, docs/searching.md, src/bgworker/normal.rs, src/gucs.rs, src/index/am_scan.rs, src/ipc/client/mod.rs, src/ipc/packet/mod.rs, src/ipc/server/mod.rs
Fix #194 
It's a bad idea to straightly pass parameter `nprobe` to all indexes, as only `ivf` need it.
However, for `ipc` caller `am_scan`, it's transparent of index type in use, as it is parsed at callee `service`, so we could not construct an union before `am_scan`.
Thus, we create a dataclass `SearchGucs` which could handle runtime variables for both `sealed` and `growing` segments.
And `SealedSearchGucs` which contains `ivf_probe` and other future required runtime variables, it could handle all runtime variables for sealed indexes, thus approprate to pass to all indexes.
If there is other idea for the design, I would be happy to know.
- Introduce `SearchGucs` for gucs accessed by `search` method
- Introduce `SealedSearchGucs` for gucs accessed by `sealed segments search` method
- …
=> feat: add nprobe into guc

crates/service/src/index/mod.rs, crates/service/src/index/segments/growing.rs, crates/service/src/index/segments/sealed.rs, crates/service/src/utils/dir_ops.rs, docs/indexing.md, src/index/views.rs
- fix #185 
```log
vectors=# select tablerelid, idx_size from pg_vector_index_info ;
tablerelid | idx_size                                         
16873 | 4
(1 row)
```
=> feat: show index size in index info table

src/bgworker/mod.rs, src/lib.rs
I'm not sure if it really works. On my machine, OOM Killer kills Postgres directly when OOM occurs so there is no chance to print a nice message, but I think users can view kernel logs on this condition.
If OOM is detected by our code, only the OOM thread (probably an optimizing thread) will be killed. Then optimizing stops. Users will view our logs to know OOM occurs.
If the background process is killed but Postgres is not killed, the background process just restarts after 1 second. OOM probably occurs again (since it's raisen from an optimizing).
Will it close #208 ?
=> chore: friendly OOM message

crates/service/src/algorithms/flat.rs, crates/service/src/algorithms/hnsw.rs, crates/service/src/algorithms/ivf/ivf_naive.rs, crates/service/src/algorithms/ivf/ivf_pq.rs, crates/service/src/algorithms/ivf/mod.rs, crates/service/src/index/indexing/flat.rs, crates/service/src/index/indexing/hnsw.rs, crates/service/src/index/indexing/ivf.rs, crates/service/src/index/indexing/mod.rs, crates/service/src/index/mod.rs, crates/service/src/index/segments/growing.rs, crates/service/src/index/segments/mod.rs, crates/service/src/index/segments/sealed.rs, crates/service/src/instance/mod.rs, crates/service/src/utils/iter.rs, crates/service/src/utils/mod.rs, crates/service/src/worker/mod.rs, src/bgworker/normal.rs, src/index/am_scan.rs, src/ipc/client/mod.rs, src/ipc/packet/mod.rs, src/ipc/server/mod.rs
=> refactor: rework vbase

src/datatype/casts_f32.rs, src/datatype/operators_f16.rs, src/datatype/operators_f32.rs, src/datatype/typmod.rs, src/datatype/vecf16.rs, src/datatype/vecf32.rs, src/embedding/udf.rs, src/index/am.rs, src/index/views.rs, src/lib.rs, src/sql/bootstrap.sql, src/sql/finalize.sql
* PR in pgvecto.rs: https://github.com/tensorchord/pgvecto.rs/pull/254
* PR in pgvecto.rs-docs: https://github.com/tensorchord/pgvecto.rs-docs/pull/8
Currently we rely on pgrx to generate SQL schema. However it's hard to track generated schema and write a update script.
We will:
* do not use `pg_*` macros, expect for `pg_extern` attached to `_vectors_*`
* write schema in `finalize.sql`
* document schema in pgvecto.rs-docs
=> chore: stable schema generation

src/datatype/casts_f32.rs, src/sql/finalize.sql, tests/sqllogictest/cast.slt
This adds the ability to cast vectors to vecf16.  Partially addressing #255 and closing #262, which specifically requests only this functionality.
=> feat: Add vector to vecf16 CAST

Cargo.toml, docker/pgvecto-rs.Dockerfile, scripts/ci_install.sh, src/bin/pgrx_embed.rs, src/datatype/vecf16.rs, src/datatype/vecf32.rs, src/index/am_setup.rs, src/index/views.rs, src/sql/finalize.sql, vectors.control
* pgvecto.rs: https://github.com/tensorchord/pgvecto.rs/pull/273
* pgvecto.rs-docs: https://github.com/tensorchord/pgvecto.rs-docs/pull/19
closes #270
=> chore: set schema and search_path

src/gucs/planning.rs, src/index/compat.rs, src/index/hooks.rs, src/index/mod.rs, tests/sqllogictest/compat.slt
Fix #227 
- Add new Gucs `SET vectors.pgvector_compat=on` to enable/disable statement rewrite
- Function `pgvector_compat_rewrite` would be used to edit these elements
- accessMethod -> from `hnsw/ivfflat` to `vectors`
- opclass -> from `vector_ip_ops/vector_cosine_ops` to `vector_dot_ops/vector_cos_ops`
- options -> from `m: int/ef_construction: int/list: int` to `options: serialized toml`
- Test file `compact.slt` for pgvector-style SQL statements
These statments would be acceptable from now:
```sql
CREATE INDEX hnsw_l2_index ON t USING hnsw (val vector_l2_ops);
CREATE INDEX hnsw_ip_index ON t USING hnsw (val vector_ip_ops) WITH (ef_construction = 80);
CREATE INDEX hnsw_cosine_index ON t USING hnsw (val vector_cosine_ops) WITH (m = 12, ef_construction = 80);
CREATE INDEX ivf_l2_index ON …
```
=> feat: add compat with pgvector

crates/service/src/algorithms/clustering/elkan_k_means.rs, crates/service/src/utils/vec2.rs
Thanks to @xieydd , we have digged out this bug.
```rust
Panickied. Info: PanicInfo { payload: Any { .. }, 
message: Some(attempt to subtract with overflow), 
location: Location { file: "crates/service/src/algorithms/clustering/[elkan_k_means.rs](http://elkan_k_means.rs/)", line: 179, col: 47 }, 
can_unwind: true, force_no_backtrace: false }
```
If there is too few vectors with a small count `n` and larger `nlist as c`, it will be a `overflow` there.
=> fix: prevent overflow at kmeans

src/gucs/executing.rs, src/index/compat.rs, tests/sqllogictest/compact_stmt.slt, tests/sqllogictest/compact_var.slt
Fix #295 
Related to #256 and #227
From now, we support `vectors.ivf_nprobe` and `vectors.hnsw_ef_search` like `pgvector` through overwrite.
However, their default value is not the same as pgvector.
* https://github.com/tensorchord/pgvecto.rs-docs/pull/14
=> feat: support pgvector gucs compact

.github/workflows/nightly.yml, .github/workflows/release.yml
- fix #142 
- nightly will only have only one release and it will edit this release if there are changes in 24h
- nightly will trigger the release action through an release created/edited event
- release will be triggered with GitHub Release, so we won't be able to push the version change commit to this tag, we only modify the code in the release
- replaces several archived actions with gh cli
- generated release note cannot group the PRs since we don't have tags on PRs, otherwise this can be done with a https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
=> chore: update the release & nightly action

.github/workflows/nightly.yml, .github/workflows/release.yml
- align the nightly tag
- change to a nightly token that has permission to trigger another workflow
According to the GitHub [trigger a workflow from a workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow), the default `GITHUB_TOKEN` cannot trigger another workflow. Thus it requires a personal access token.
You can follow the instructions [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token) to generate a repository level token and save it to this repo setting with the name `NIGHTLY_TOKEN`. It requires the following read/write permission:
- actions
- contents
cc @VoVAllen
=> chore: nightly token that can trigger the release workflow

src/sql/finalize.sql, tests/sqllogictest/vecf16_storage.slt, tests/sqllogictest/vector_storage.slt
Pref result shows PostgreSQL compression affects insertion performance largely so we disable it.
Bench code and result: https://gist.github.com/usamoi/ce1b8a9fd806dcca2bcea438b2fdffa2 (based on #314)
=> chore: set storage = EXTERNAL by default for vector types

Cargo.lock, crates/c/tests/x86_64.rs, crates/detect/Cargo.toml, crates/detect/src/lib.rs, crates/detect/src/linux.rs, crates/detect/src/x86_64.rs, crates/detect/tests/linux.rs, crates/detect/tests/x86_64.rs, src/lib.rs
For reference: https://github.com/mmastrac/rust-ctor/issues/280
The simplest solution is to just remove it.
=> fix: remove ctor

src/datatype/vecf16.rs, src/datatype/vecf32.rs, tests/sqllogictest/pg14/vecf16_subscript.slt, tests/sqllogictest/pg14/vector_subscript.slt
Current subslice behavior is consistent with PostgreSQL:
```
SELECT ('{0, 1, 2, 3, 4, 5, 6, 7}'::real[])[3:6];
float4   
-----------
{2,3,4,5}
(1 row)
SELECT ('[0, 1, 2, 3, 4, 5, 6, 7]'::vector)[3:6];
vector   
-----------
[2, 3, 4, 5]
(1 row)
```
Making it consistent with Python should be better.
```
>>> [0, 1, 2, 3, 4, 5, 6, 7][3:6]
[3, 4, 5]
SELECT ('[0, 1, 2, 3, 4, 5, 6, 7]'::vector)[3:6];
vector   
-----------
[3, 4, 5]
(1 row)
```
=> chore: consistent slice behavior with Python

src/index/am.rs, src/index/am_build.rs, src/index/am_scan.rs, src/index/utils.rs, tests/sqllogictest/null.slt
Fix #386 
Part of #376 , we still need a patch for upgrade to v0.2.0
=> fix: support null insert

src/index/am.rs, src/index/am_build.rs, src/index/am_scan.rs, src/index/utils.rs, tests/sqllogictest/null.slt
cherry pick of #390 
We still need to upgrade some of docs at https://docs.pgvecto.rs/admin/upgrading.html as:
- Delete existing index at NULL-possible column to avoid crash
- Take `kubectl delete pod/kubectl rollout restart` instead of `kubectl cnpg restart` to avoid #387
=> fix: support null insert (#390)

src/bgworker/normal.rs
Fix #387 
SIGTERM and SIGQUIT are used at postgres shutdown
https://www.postgresql.org/docs/current/server-shutdown.html
=> fix: remove sighup handler

src/datatype/subscript_bvecf32.rs, tests/sqllogictest/bvector_subscript.slt
Sorry. I forget to consider the situation of `end % BVEC_WIDTH == 0`.
=> fix: bvector subscription may modify padding bits 

sql/upgrade/vectors--0.1.10--0.2.0.sql
Test of upgrade from v0.1.10 to v0.2.0 still failed for unexist symbol `vector_stat`. This is the fix for it.
=> fix: upgrade from v0.1.10

src/sql/finalize.sql
=> fix: grant permission for `pg_vector_index_stat` in install sql

crates/base/src/vector/veci8.rs
Tests may fails when the cosine result is small.
Just add a check for small result.
=> fix: relax veci8 test precision.

.github/workflows/release.yml, scripts/build_2.sh, sql/upgrade/vectors--0.1.10--0.2.0.sql
=> chore: cherry back 0.2 branch

README.md
=> Update pgvecto.rs README.md with new features and documentation link

crates/base/src/search.rs, crates/service/src/version.rs, src/index/utils.rs
=> fix: take `MyDatabaseId` into handle to resolve conflicts of OIDs in multidatabases

Cargo.toml, crates/base/src/index.rs
I found that IndexOption check for vecint8 is lost when I merge branch.
=> fix: validate_index for veci8 & rm deprecated feature.

src/gucs/embedding.rs, tests/sqllogictest/openai_options.slt
I think those code don't matchs.
```rust     
let base_url = guc_string_parse(&OPENAI_BASE_URL, "vectors.openai_base");
```
and 
```rust
GucRegistry::define_string_guc(
"vectors.openai_base_url",
"The base url of OpenAI or compatible server.",
"",
&OPENAI_BASE_URL,
GucContext::Userset,
GucFlags::default(),
);
```
=> fix: fix openai option gucs setting.

crates/elkan_k_means/src/operator.rs, crates/ivf/src/ivf_naive.rs, crates/ivf/src/ivf_pq.rs
Does Elkan k-means work for Jaccard distance?
=> fix: elkan K-means impl for some vector types

src/sql/finalize.sql
=> fix: skip partitioned tables in `pg_vector_index_stat`

crates/base/src/scalar/f32.rs, crates/base/src/scalar/half_f16.rs
f*_algebraic intrinsics are safer than f*_fast intrinsics since they do not assume inputs are not NaNs or Inf.
=> fix: use f*_algebraic intrinsics, instead of f*_fast intrinsics

src/datatype/operators_svecf32.rs, src/datatype/operators_vecf16.rs, src/datatype/operators_vecf32.rs, src/datatype/operators_veci8.rs, src/sql/finalize.sql, tests/sqllogictest/fp16.slt, tests/sqllogictest/int8.slt, tests/sqllogictest/sparse.slt, tests/sqllogictest/vector.slt
=> feat: support element-wise multiplication.

src/datatype/text_svecf32.rs, src/error.rs, src/utils/parse.rs, tests/sqllogictest/sparse.slt, tests/sqllogictest/svector.slt, tests/sqllogictest/svector_subscript.slt
Part of #459 
- Changed svector text representation from "[0, 1, 0, 3, 4]" to pgvector-style "{2:1, 4:3, 5:4}/5"
- Upgraded toolchain for new feature `proc_macro_byte_character` from upstream
The index is from ***1*** instead of 0 at pgvector
| Old                      | New                                   |
| ------------------------ | ------------------------------------- |
| [0, 1, 2, 0, 0]          | {1:1, 2:2}/5                          |
| [0, 1, 2, 3, 4, 5, 6, 7] | {1:1, 2:2, 3:3, 4:4, 5:5, 6:6, 7:7}/8 |
| [5, 6, 7]                | {0:5, 1:6, 2:7}/3                     |
| [0, 0, 0, 0]             | {}/4                                  |
=> feat: new text representation for sparse vector

src/index/functions.rs, src/sql/finalize.sql
Add a util function that helps block the thread until an index is ready after bulk insertions and deletions.
=> feat: add util function `fence_vector_index`

.github/workflows/psql.yml
`sqllogictest-bin` fails to build on CI sometimes, causing that `cargo-binstall` on CI does not really work.
=> ci: lock version of sqllogictest-bin

tests/sqllogictest/cos.slt
`hnsw_ef_search` is 100, so we cannot get exact top-100 KNN search results.
=> test: fix cos test by comparing shorter result list

crates/ivf/src/ivf_naive.rs, crates/ivf/src/ivf_residual.rs, crates/k_means/src/elkan.rs, crates/k_means/src/lib.rs, crates/k_means/src/lloyd.rs, crates/k_means/src/quick_centers.rs, crates/quantization/src/product/mod.rs, crates/rabitq/src/lib.rs, tests/sqllogictest/bvector.slt
K-means++ generates clusters that are not balanced, so disables it in IVF.
=> feat: disable kmeans++ in IVF

crates/base/src/scalar/f16.rs
`_mm_loadu_epi16` is accidentally used in code for fp16 in AVX. However, rustc emits `vmovups` for `_mm_loadu_epi16`, instead of `vmovdqu16`. So the tests passed in CI without segmentation fault.
=> fix: use correct intrinsics for fp16 in AVX

crates/base/src/index.rs, crates/quantization/src/product.rs
With this PR, on GIST, (nlist = 4096, residual_quantization = true; nprobe = 300)
* IVF-RQ 0.9843 2.5s
* IVF-PQ 0.9914 3.3s (ratio = 2, bits = 2; pq_rerank_size = 100)
=> refactor: use transposed centroids in PQ preprocess

src/gucs/embedding.rs, src/gucs/mod.rs
PostgreSQL do not emit errors if a GUC setting does not exist by default since the extension that needs it may not be loaded when a GUC setting is set. Marking GUC prefix reserved would help users to realize that they set incorrect options.
=> feat: mark GUC prefix reserved

README.md
Fix https://github.com/tensorchord/pgvecto.rs/issues/626
=> chore: Fix links
